# Generated by Django 5.0.4 on 2024-04-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='active',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='alpha1',
        ),
        migrations.AddField(
            model_name='countries',
            name='alpha3',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='countries',
            name='alpha2',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
